### ISSUE TITLE
error bootstrapping test keycloak

### ISSUE THREAD

**Issue by strantalis** [opentdf/platform#620]
Getting the following error when tyring to bootstrap keycloak for testing. 

```
2024/04/18 21:57:24 INFO ✅ User created: username = sampleuser, user identifier=a954bc3d-6d29-4bde-aa71-c8d4f421f152
2024/04/18 21:57:25 ERROR Error creating management permissions : 500 Internal Server Error: unknown_error: For more on this error consult the server log at the debug level.
Error: 500 Internal Server Error: unknown_error: For more on this error consult the server log at the debug level.
```

Keycloak Logs

```
2024-04-19 01:57:25,744 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-1) Uncaught server error: java.lang.NullPointerException: Cannot invoke "org.keycloak.authorization.model.Resource.getId()" because the return value of "org.keycloak.services.resources.admin.permissions.ClientPermissionManagement.resource(org.keycloak.models.ClientModel)" is null
at org.keycloak.services.resources.admin.ClientResource.toMgmtRef(ClientResource.java:717)
at org.keycloak.services.resources.admin.ClientResource.setManagementPermissionsEnabled(ClientResource.java:741)
at org.keycloak.services.resources.admin.ClientResource$quarkusrestinvoker$setManagementPermissionsEnabled_c26892ab4991faf7866b743f4b0af3c44c612c78.invoke(Unknown Source)
at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:582)
at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
at java.base/java.lang.Thread.run(Thread.java:840)
```

**Comment by strantalis** [comment]
This was an issue with not having `preview` features enabled.
