### ISSUE TITLE
health check service failure

### ISSUE THREAD

**Issue by strantalis** [opentdf/platform#699]
The health check endpoint executed a `Ping` against the db to check if it was accessible. With the new db changes we lost the ability to execute this check. The endpoint is now producing a `panic` with a nil pointer dereference to that client. 

Logs

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1486afa]
goroutine 158 [running]:
github.com/opentdf/platform/service/health.HealthService.Check({{}, 0x414500?}, {0x1bee090?, 0xc0001f5da0?}, 0xc000794528?)
/app/service/health/health.go:51 +0x7a
google.golang.org/grpc/health/grpc_health_v1._Health_Check_Handler({0x1679ae0, 0xc000424258}, {0x1bee090, 0xc0001f5da0}, 0xc00036eb00, 0x0)
/root/go/pkg/mod/google.golang.org/grpc@v1.63.2/health/grpc_health_v1/health_grpc.pb.go:184 +0x1a6
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00031ae00, {0x1bee090, 0xc0000caa50}, {0x1bf9660, 0xc00032e600}, 0xc00039c480, 0xc000329710, 0x278f8f0, 0x0)
/root/go/pkg/mod/google.golang.org/grpc@v1.63.2/server.go:1369 +0xdf8
google.golang.org/grpc.(*Server).handleStream(0xc00031ae00, {0x1bf9660, 0xc00032e600}, 0xc00039c480)
/root/go/pkg/mod/google.golang.org/grpc@v1.63.2/server.go:1780 +0xe8b
google.golang.org/grpc.(*Server).serveStreams.func2.1()
/root/go/pkg/mod/google.golang.org/grpc@v1.63.2/server.go:1019 +0x8b
created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 126
/root/go/pkg/mod/google.golang.org/grpc@v1.63.2/server.go:1030 +0x125
```

**Comment by strantalis** [comment]
Closing this in favor of tracking via #700
