### ISSUE TITLE
Docker compose up fails to start keycloak

### ISSUE THREAD

**Issue by jrschumacher** [opentdf/platform#822]
On origin/main 41ca82d692209d120bfa52800fa0988bf373b0b5 `docker compose up` fails to start keycloak which prohibits running the platform.

```
eycloak-1  | java.lang.RuntimeException: Failed to start quarkus
keycloak-1  | 	at io.quarkus.runner.ApplicationImpl.<clinit>(Unknown Source)
keycloak-1  | 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
keycloak-1  | 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
keycloak-1  | 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
keycloak-1  | 	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
keycloak-1  | 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
keycloak-1  | 	at io.quarkus.runtime.Quarkus.run(Quarkus.java:70)
keycloak-1  | 	at org.keycloak.quarkus.runtime.KeycloakMain.start(KeycloakMain.java:117)
keycloak-1  | 	at org.keycloak.quarkus.runtime.cli.command.AbstractStartCommand.run(AbstractStartCommand.java:33)
keycloak-1  | 	at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
keycloak-1  | 	at picocli.CommandLine.access$1500(CommandLine.java:148)
keycloak-1  | 	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
keycloak-1  | 	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
keycloak-1  | 	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
keycloak-1  | 	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
keycloak-1  | 	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
keycloak-1  | 	at picocli.CommandLine.execute(CommandLine.java:2170)
keycloak-1  | 	at org.keycloak.quarkus.runtime.cli.Picocli.parseAndRun(Picocli.java:125)
keycloak-1  | 	at org.keycloak.quarkus.runtime.KeycloakMain.main(KeycloakMain.java:107)
keycloak-1  | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
keycloak-1  | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
keycloak-1  | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
keycloak-1  | 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
keycloak-1  | 	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:62)
keycloak-1  | 	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:33)
keycloak-1  | Caused by: java.lang.RuntimeException: Failed to initialize TruststoreProviderFactory: /truststore/truststore.jks, truststore type: JKS
keycloak-1  | 	at org.keycloak.truststore.FileTruststoreProviderFactory.init(FileTruststoreProviderFactory.java:111)
keycloak-1  | 	at org.keycloak.quarkus.runtime.integration.QuarkusKeycloakSessionFactory.<init>(QuarkusKeycloakSessionFactory.java:83)
keycloak-1  | 	at org.keycloak.quarkus.runtime.KeycloakRecorder.configSessionFactory(KeycloakRecorder.java:104)
keycloak-1  | 	at io.quarkus.deployment.steps.KeycloakProcessor$configureKeycloakSessionFactory343981823.deploy_4(Unknown Source)
keycloak-1  | 	at io.quarkus.deployment.steps.KeycloakProcessor$configureKeycloakSessionFactory343981823.deploy(Unknown Source)
keycloak-1  | 	... 25 more
keycloak-1  | Caused by: java.io.FileNotFoundException: /truststore/truststore.jks (Is a directory)
keycloak-1  | 	at java.base/java.io.FileInputStream.open0(Native Method)
keycloak-1  | 	at java.base/java.io.FileInputStream.open(FileInputStream.java:216)
keycloak-1  | 	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
keycloak-1  | 	at org.keycloak.common.util.KeystoreUtil.loadKeyStore(KeystoreUtil.java:80)
keycloak-1  | 	at org.keycloak.truststore.FileTruststoreProviderFactory.init(FileTruststoreProviderFactory.java:101)
```

To resolve this issue see acceptance criteria

## Acceptance Criteria

- update the README to give clarity around this issue and provide accurate solution
- update the docker-compose.yaml to either automate the creation of these keys OR give better error messages
- add an automated test around smoke tests using the docker-compose.yaml file

**Comment by namanrawal47** [comment]
This is because sometimes the certs, keys, and keystore are being created as directories for some reason. I referenced it here: https://github.com/opentdf/platform/issues/778

You might want to check that the truststore is being created as a file and not a directory. If it's a dir, delete it and rerun the init script. Hopefully that solves your issue.

**Comment by jrschumacher** [comment]
The issue here is twofold:

1. You **MUST** run `./.github/scripts/init-temp-keys.sh` before running `docker compose up`
2. If you ran them inverse... you must remove the keys directory since `docker` will have created directories for any missing file mounted as a volume `rm -r ./keys`

Updating the description to capture acceptance criteria.

**Comment by namanrawal47** [comment]
I added something like this to my version of the script in case I needed to run it multiple times for any reason.
```
#!/bin/sh
# init-temporary-keys.sh
# Initialize temporary keys for use with a KAS

USAGE="Usage:  ${CMD:=${0##*/}} [(-v|--verbose)] [-H|--hsm] [-o|--output <path>]"
KEYS_DIR="$(pwd)/keys"
CA_JKS="${KEYS_DIR}/ca.jks"
LOCALHOST_KEY="${KEYS_DIR}/localhost.key"
LOCALHOST_CRT="${KEYS_DIR}/localhost.crt"

# Function to check file or directory status and take appropriate action
check_and_handle_path() {
    local path=$1
    local name=$2

    if [[ -d "${path}" ]]; then
        echo "'${name}' is a directory. Removing it..."
        rm -rf "${path}"
    elif [[ -f "${path}" ]]; then
        echo "'${name}' is a file. File type:"
        file "${path}"
        echo "'${name}' already exists."
    else
        echo "'${name}' does not exist. Continuing..."
    fi
}

check_and_handle_path "${CA_JKS}" "ca.jks"
check_and_handle_path "${LOCALHOST_KEY}" "localhost.key"
check_and_handle_path "${LOCALHOST_CRT}" "localhost.crt"
```

**Comment by jrschumacher** [comment]
@namanrawal47 feel free to reopen or create a new issue if you run into this again.
